DROP DATABASE IF EXISTS tpdb;
DROP USER IF EXISTS `tpadmin`@`%`;
DROP USER IF EXISTS `tpapp`@`%`;
CREATE DATABASE IF NOT EXISTS tpdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `tpadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `tpdb`.* TO `tpadmin`@`%`;
CREATE USER IF NOT EXISTS `tpapp`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `tpdb`.* TO `tpapp`@`%`;
FLUSH PRIVILEGES;