DROP DATABASE IF EXISTS rulesdb;
DROP USER IF EXISTS `rulesadmin`@`%`;
DROP USER IF EXISTS `rulesapp`@`%`;
CREATE DATABASE IF NOT EXISTS rulesdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `rulesadmin`@`%` IDENTIFIED BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `rulesdb`.* TO `rulesadmin`@`%`;
CREATE USER IF NOT EXISTS `rulesapp`@`%` IDENTIFIED BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `rulesdb`.* TO `rulesapp`@`%`;
FLUSH PRIVILEGES;